service: direct-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: src/handler.index
    events:
      - http:
          path: company
          method: post
          cors: true
      - http:
          path: company
          method: get
          cors: true